# MongoDB configuration file
# Place this file in your project root or a preferred location

storage:
  dbPath: D:\data\db

net:
  port: 27017
  bindIp: 127.0.0.1

systemLog:
  destination: file
  path: D:\Freelance Projects\SmartEyeCare\mongod.log
  logAppend: true
